---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cadency.fullname" . }}
  labels:
    {{- include "cadency.labels" . | nindent 4 }}
data:
  {{- with .Values.cadency.config }}
  logLevel: {{ .logLevel }}
  playlistSongLimit: {{ .playlistSongLimit }}
  songLengthLimit: {{ .songLengthLimit }}
  {{- end }}
