{{- if .Values.cadency.discordToken.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadency.fullname" . }}
  labels:
    {{- include "cadency.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.cadency.discordToken.token | b64enc }}
{{- end }}
