name: Development
on:
  push:
    branches:
      - develop

jobs:
  test_branch:
    name: Test Dev branch
    uses: ./.github/workflows/test.yml
  publish_image:
    permissions: 
      contents: read
      packages: write
    needs:
      - test_branch
    name: Publish dev image
    uses: ./.github/workflows/image.yml
    with:
      user: jontze
      push: true
      cache_tag: develop
    secrets: inherit
