name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  test_release:
    name: Test Main
    uses: ./.github/workflows/test.yml

  publish_image:
    permissions:
      contents: read
      packages: write
    needs:
      - test_release
    name: Publish main image
    uses: ./.github/workflows/image.yml
    with:
      user: jontze
      push: true
    secrets: inherit

  create_gh_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - publish_image
    name: Create GitHub Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
